new progress
dezmag/EasyIT-course pull request #4
Opened 2020-09-06 10:28 UTC by dezmag

2020-09-06 18:10 UTC, bloodybaker requested changes
Исправления по поводу первого коммита. Старайтесь писать разные названия коммитов, а то в них легко запутаться

2020-09-06 18:10 UTC, bloodybaker commented on src/com/company/task2/Friend.java
> +    private  String say;
Друг это тоже человек, унаследуйте его

2020-09-06 18:10 UTC, bloodybaker commented on src/com/company/task2/Main.java
> +        Friend friend = new Friend("Harry",13,"I am friend");
Не создавайте объект если вы его не будете использовать, а просто передайте конструктор в качестве параметра

2020-09-06 18:11 UTC, bloodybaker reviewed
Тут выглядит всё хорошо

2020-09-06 18:13 UTC, bloodybaker requested changes
На исправления

2020-09-06 18:13 UTC, bloodybaker commented on src/com/company/task2/Main.java
> +       //girl.getInf();
Убирайте комментарии

2020-09-06 18:13 UTC, bloodybaker commented on src/com/company/task2/Main.java
> +       Human boy= new Boy("Jack",20,1.85,75,hobby,friend);
Передавайте сразу конструктор в конструктор (описал в ревью раньше)

2020-09-06 19:22 UTC, dezmag commented on src/com/company/task2/Main.java
> +       Human boy= new Boy("Jack",20,1.85,75,hobby,friend);
Переделал, но мне просто не всё понятно я на уроку задам вопросы может у кого то тоже нечто подобное.

2020-09-06 19:23 UTC, bloodybaker commented on src/com/company/task2/Main.java
> +       Human boy= new Boy("Jack",20,1.85,75,hobby,friend);
Окей

2020-09-06 19:24 UTC, bloodybaker reviewed
Посмотрите замечание

2020-09-06 19:24 UTC, bloodybaker commented on src/com/company/task2/Main.java
> +         Girl girl = new Girl("Anna",19,1.79,60,hobby,friend);
О чем я именно говорил:
`Girl girl =  new Girl("Anna",19,1.79,60, new Hobby(" football", 2," The game where players kick the ball"),new Friend("Harry",13,"I am friend"))`
вместо 3х строчек

2020-09-07 07:13 UTC, dezmag commented on src/com/company/task2/Main.java
> +         Girl girl = new Girl("Anna",19,1.79,60,hobby,friend);
Ну собственно вот я и не додумался до этого

2020-09-07 08:35 UTC, bloodybaker approved these changes
Выглядит хорошо, можно сливать ветки

2020-09-07 15:59 UTC, merged